[profile.dev.package."*"]
opt-level = 3
[profile.dev.package.app]
opt-level = 0
[profile.dev.package.server]
opt-level = 0

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
strip = "debuginfo"

[workspace]
members = ["app", "entity", "migration", "server", "wasm-lib"]

[workspace.dependencies]
leptos = "0.2.1"
leptos_meta = "0.2.1"
leptos_router = "0.2.1"
leptos_dom = "0.2.1"
leptos_axum = "0.2.0"

[[workspace.metadata.leptos]]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle. Defaults to the crate name
name = "todo-vault"
output-name = "todo-vault"
site-root = "target/site"
assets-dir = "public"
site-pkg-dir = "pkg"
style-file = "style/main.sass"
site-addr = "127.0.0.1:3000"
bin-package = "server"
lib-package = "wasm-lib"
