[toolchain]
channel = "nightly-2023-07-16"
components = ["cargo", "miri", "rustfmt", "rustc-dev", "rust-analyzer", "rust-src"]
profile = "default"
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
