[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
app = { path = "../app", default-features = false, features = ["ssr"] }
leptos = { workspace = true, features = ["serde", "ssr"] }
leptos_meta = { workspace = true, features = ["ssr"] }
leptos_router = { workspace = true, features = ["ssr"] }
leptos_dom = { workspace = true, features = ["ssr"] }
leptos_axum.workspace = true

axum = "0.6.4"
derive_more = "0.99.17"
console_error_panic_hook = "0.1"
console_log = "0.2"
log = "0.4"
simple_logger = "4"
tokio = "1.25.0"
tower = "0.4.13"
tower-http = { version = "0.3.5", features = ["fs"] }
wasm-bindgen = "0.2"
thiserror = "1.0.38"
tracing = { version = "0.1.37" }
http = "0.2.9"
